#!/usr/bin/env node
const express = require('express')
const app = express()
const server = require("./app") // load up the web server
const io = require('socket.io')
const port = 3000 // the port to listen to for incoming requests

// uuidV4() generates unique identifier 
const { v4:uuidV4 } = require('uuid')

// when createRoom called generate a unique uuid and reroute to it 
app.get('/createRoom', (req, res) => {
  res.redirect(`/${uuidV4() }`)
})

// renders page with unique uuid generated by createRoom
app.get('/:room', (req, res) => {
  res.render('room', { roomId:req.params.room })
})

// call express's listen function to start listening to the port
const listener = server.listen(port, function () {
  console.log(`Server running on port: ${port}`)
})

// a function to stop listening to the port
const close = () => {
  listener.close()
}

module.exports = {
  close: close,
}